CREATE TRIGGER TRG_CREATE_EMP_DETAILS AFTER INSERT ON EMPLOYEES
BEGIN
INSERT INTO EMPLOYEE_ADDRESS (emp_id) VALUES (NEW.emp_id);
INSERT INTO EMPLOYEE_PERMISSIONS (emp_id) VALUES (NEW.emp_id);
INSERT INTO EMPLOYEE_PTO (emp_id) VALUES (NEW.emp_id);
INSERT INTO EMPLOYEE_CREDENTIALS (emp_id) VALUES (New.emp_id);
END;